# Generated by Django 3.2.3 on 2021-05-26 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
